name: CI
on: [push, pull_request]

jobs:

  linux-32:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - run: |
          sudo apt-get update -qqy
          sudo apt-get install -qqy \
            cmake \
            make \
            gcc \
            libz-dev \
            zlib1g-dev \
            libpng-dev \
            libsdl2-dev \
            libvorbis-dev \
            libalut-dev \
            libmbedtls-dev \
            libturbojpeg0-dev \
            libuv1-dev \
            libopenal-dev \
            neko \
            curl \
            ca-certificates

      - run: make
    
  linux-64:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qqy
          sudo apt-get install -qqy \
            cmake \
            make \
            gcc-multilib \
            libz-dev:i386 \
            zlib1g-dev:i386 \
            libpng-dev:i386 \
            libsdl2-dev:i386 \
            libvorbis-dev:i386 \
            libalut-dev:i386 \
            libmbedtls-dev:i386 \
            libturbojpeg0-dev:i386 \
            libuv1-dev:i386 \
            libopenal-dev:i386 \
            neko \
            curl \
            ca-certificates

      - run: make

  macos:
    runs-on: macos-10.15
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - run: |
          brew update
          brew install neko
          brew bundle
          brew install mbedtls@2
      
      - run: make

  windows:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - uses: microsoft/setup-msbuild@v1.0.2

      - uses: Amadevus/pwsh-script@v2
        with:
          script: |
            Invoke-WebRequest https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip -OutFile SDL.zip
            Expand-Archive SDL.zip -DestinationPath .
            Move-Item SDL2-* include/sdl
            Remove-Item SDL.zip
      - uses: Amadevus/pwsh-script@v2
        with:
          script: |
            Invoke-WebRequest http://openal-soft.org/openal-binaries/openal-soft-1.17.2-bin.zip -OutFile openal.zip
            Expand-Archive openal.zip -DestinationPath .
            Move-Item openal-* include/openal
            Remove-Item openal.zip
      - uses: Amadevus/pwsh-script@v2
        with:
          script: |
            Invoke-WebRequest https://github.com/HaxeFoundation/hashlink/files/5648056/ffmpeg-3.4.2-win64-dev.zip -OutFile ffmpeg.zip
            Expand-Archive ffmpeg.zip -DestinationPath .
            Move-Item ffmpeg-* include/ffmpeg
            Remove-Item ffmpeg.zip
      - uses: Amadevus/pwsh-script@v2
        with:
          script: |
            Set-Service wuauserv -StartupType Manual
            choco install --no-progress neko -y
            $nekoPath = (Get-ChildItem C:/ProgramData/chocolatey/lib/neko/*/neko.dll -Recurse).Directory
            Write-Host "##vso[task.setvariable variable=NEKOPATH]$nekoPath"
      
      - run: MSBuild hl.sln /nologo /clp:ErrorsOnly "-p:Configuration=Release;PlatformToolset=v142;WindowsTargetPlatformVersion=10"
